services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MartenConnectionString: Host=postgres;Port=5432;Username=postgres;Password=postgres;Database=postgres
    ports:
      - "5074:5074"
    depends_on:
      - postgres

volumes:
  postgres_data: